### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by oneryx** [lolo101/MsgViewer#110]
I got following exception while opening a msg file with attachments.
```
2022-06-21T18:45:08,208 ERROR (AutoMBox.java:30): Exception: java.lang.NullPointerException
null
java.lang.NullPointerException: null
        at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:75) ~[?:?]
        at sun.nio.fs.UnixPath.<init>(UnixPath.java:69) ~[?:?]
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279) ~[?:?]
        at java.nio.file.Path.resolve(Path.java:515) ~[?:?]
        at net.sourceforge.MSGViewer.ViewerHelper.getTempFile(ViewerHelper.java:154) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerHelper.getTempFile(ViewerHelper.java:144) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.printFileAttachment(ViewerPanel.java:525) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.printAttachment(ViewerPanel.java:515) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.printAttachments(ViewerPanel.java:508) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.headerHtml(ViewerPanel.java:471) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.updateHeader(ViewerPanel.java:460) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.doParse(ViewerPanel.java:437) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.invoke(AutoMBox.java:27) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.<init>(AutoMBox.java:18) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.<init>(AutoMBox.java:22) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.parse(ViewerPanel.java:428) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.view(ViewerPanel.java:105) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.EditorDropTarget.lambda$dropFile$0(EditorDropTarget.java:149) ~[msgviewer.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at net.sourceforge.MSGViewer.EditorDropTarget.dropFile(EditorDropTarget.java:147) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.EditorDropTarget.drop(EditorDropTarget.java:77) ~[msgviewer.jar:?]
```

To track what's going on, I added a `System.out.printf` here
```java
    public static Pid from(int id, Ptyp typ) {
        System.out.printf("Parsing Pid: %d, 0x%X, typ: %s\n", id, id, typ.name());
        return Arrays.stream(Pid.values())
                .filter(value -> value.id == id)
                .filter(value -> value.typ == typ)
                .findFirst()
                .orElse(Unknown);
    }
```

which got following output for my msg file
```
Parsing Pid: 3093, 0xC15, typ: PtypInteger32
Parsing Pid: 3599, 0xE0F, typ: PtypBoolean
Parsing Pid: 4089, 0xFF9, typ: PtypBinary
Parsing Pid: 4094, 0xFFE, typ: PtypInteger32
Parsing Pid: 4095, 0xFFF, typ: PtypBinary
Parsing Pid: 12289, 0x3001, typ: PtypString8
Parsing Pid: 12290, 0x3002, typ: PtypString8
Parsing Pid: 12291, 0x3003, typ: PtypString8
Parsing Pid: 12299, 0x300B, typ: PtypBinary
Parsing Pid: 14592, 0x3900, typ: PtypInteger32
Parsing Pid: 14846, 0x39FE, typ: PtypString8
Parsing Pid: 14847, 0x39FF, typ: PtypString8
Parsing Pid: 14848, 0x3A00, typ: PtypString8
Parsing Pid: 14880, 0x3A20, typ: PtypString8
Parsing Pid: 14912, 0x3A40, typ: PtypBoolean
Parsing Pid: 14961, 0x3A71, typ: PtypInteger32
Parsing Pid: 15617, 0x3D01, typ: PtypBinary
Parsing Pid: 24542, 0x5FDE, typ: PtypInteger32
Parsing Pid: 24543, 0x5FDF, typ: PtypInteger32
Parsing Pid: 24566, 0x5FF6, typ: PtypString8
Parsing Pid: 24567, 0x5FF7, typ: PtypBinary
Parsing Pid: 24573, 0x5FFD, typ: PtypInteger32
Parsing Pid: 24575, 0x5FFF, typ: PtypInteger32
Parsing Pid: 4086, 0xFF6, typ: PtypBinary
Parsing Pid: 12288, 0x3000, typ: PtypInteger32
Parsing Pid: 3093, 0xC15, typ: PtypInteger32
Parsing Pid: 3599, 0xE0F, typ: PtypBoolean
Parsing Pid: 4089, 0xFF9, typ: PtypBinary
Parsing Pid: 4094, 0xFFE, typ: PtypInteger32
Parsing Pid: 4095, 0xFFF, typ: PtypBinary
Parsing Pid: 12289, 0x3001, typ: PtypString8
Parsing Pid: 12290, 0x3002, typ: PtypString8
Parsing Pid: 12291, 0x3003, typ: PtypString8
Parsing Pid: 12299, 0x300B, typ: PtypBinary
Parsing Pid: 14592, 0x3900, typ: PtypInteger32
Parsing Pid: 14597, 0x3905, typ: PtypInteger32
Parsing Pid: 14846, 0x39FE, typ: PtypString8
Parsing Pid: 14847, 0x39FF, typ: PtypString8
Parsing Pid: 14848, 0x3A00, typ: PtypString8
Parsing Pid: 14880, 0x3A20, typ: PtypString8
Parsing Pid: 14912, 0x3A40, typ: PtypBoolean
Parsing Pid: 14961, 0x3A71, typ: PtypInteger32
Parsing Pid: 15617, 0x3D01, typ: PtypBinary
Parsing Pid: 24542, 0x5FDE, typ: PtypInteger32
Parsing Pid: 24543, 0x5FDF, typ: PtypInteger32
Parsing Pid: 24555, 0x5FEB, typ: PtypInteger32
Parsing Pid: 24559, 0x5FEF, typ: PtypInteger32
Parsing Pid: 24562, 0x5FF2, typ: PtypInteger32
Parsing Pid: 24565, 0x5FF5, typ: PtypInteger32
Parsing Pid: 24566, 0x5FF6, typ: PtypString8
Parsing Pid: 24567, 0x5FF7, typ: PtypBinary
Parsing Pid: 24573, 0x5FFD, typ: PtypInteger32
Parsing Pid: 24575, 0x5FFF, typ: PtypInteger32
Parsing Pid: 4086, 0xFF6, typ: PtypBinary
Parsing Pid: 12288, 0x3000, typ: PtypInteger32
Parsing Pid: 3093, 0xC15, typ: PtypInteger32
Parsing Pid: 3599, 0xE0F, typ: PtypBoolean
Parsing Pid: 4089, 0xFF9, typ: PtypBinary
Parsing Pid: 4094, 0xFFE, typ: PtypInteger32
Parsing Pid: 4095, 0xFFF, typ: PtypBinary
Parsing Pid: 12289, 0x3001, typ: PtypString8
Parsing Pid: 12290, 0x3002, typ: PtypString8
Parsing Pid: 12291, 0x3003, typ: PtypString8
Parsing Pid: 12299, 0x300B, typ: PtypBinary
Parsing Pid: 14592, 0x3900, typ: PtypInteger32
Parsing Pid: 14846, 0x39FE, typ: PtypString8
Parsing Pid: 14847, 0x39FF, typ: PtypString8
Parsing Pid: 14880, 0x3A20, typ: PtypString8
Parsing Pid: 14912, 0x3A40, typ: PtypBoolean
Parsing Pid: 14961, 0x3A71, typ: PtypInteger32
Parsing Pid: 15617, 0x3D01, typ: PtypBinary
Parsing Pid: 24542, 0x5FDE, typ: PtypInteger32
Parsing Pid: 24543, 0x5FDF, typ: PtypInteger32
Parsing Pid: 24555, 0x5FEB, typ: PtypInteger32
Parsing Pid: 24559, 0x5FEF, typ: PtypInteger32
Parsing Pid: 24562, 0x5FF2, typ: PtypInteger32
Parsing Pid: 24565, 0x5FF5, typ: PtypInteger32
Parsing Pid: 24566, 0x5FF6, typ: PtypString8
Parsing Pid: 24567, 0x5FF7, typ: PtypBinary
Parsing Pid: 24573, 0x5FFD, typ: PtypInteger32
Parsing Pid: 24575, 0x5FFF, typ: PtypInteger32
Parsing Pid: 4086, 0xFF6, typ: PtypBinary
Parsing Pid: 12288, 0x3000, typ: PtypInteger32
Parsing Pid: 3093, 0xC15, typ: PtypInteger32
Parsing Pid: 3599, 0xE0F, typ: PtypBoolean
Parsing Pid: 4089, 0xFF9, typ: PtypBinary
Parsing Pid: 4094, 0xFFE, typ: PtypInteger32
Parsing Pid: 4095, 0xFFF, typ: PtypBinary
Parsing Pid: 12289, 0x3001, typ: PtypString8
Parsing Pid: 12290, 0x3002, typ: PtypString8
Parsing Pid: 12291, 0x3003, typ: PtypString8
Parsing Pid: 12299, 0x300B, typ: PtypBinary
Parsing Pid: 14592, 0x3900, typ: PtypInteger32
Parsing Pid: 14597, 0x3905, typ: PtypInteger32
Parsing Pid: 14846, 0x39FE, typ: PtypString8
Parsing Pid: 14847, 0x39FF, typ: PtypString8
Parsing Pid: 14848, 0x3A00, typ: PtypString8
Parsing Pid: 14880, 0x3A20, typ: PtypString8
Parsing Pid: 14912, 0x3A40, typ: PtypBoolean
Parsing Pid: 14961, 0x3A71, typ: PtypInteger32
Parsing Pid: 15617, 0x3D01, typ: PtypBinary
Parsing Pid: 24542, 0x5FDE, typ: PtypInteger32
Parsing Pid: 24543, 0x5FDF, typ: PtypInteger32
Parsing Pid: 24566, 0x5FF6, typ: PtypString8
Parsing Pid: 24567, 0x5FF7, typ: PtypBinary
Parsing Pid: 24573, 0x5FFD, typ: PtypInteger32
Parsing Pid: 24575, 0x5FFF, typ: PtypInteger32
Parsing Pid: 4086, 0xFF6, typ: PtypBinary
Parsing Pid: 12288, 0x3000, typ: PtypInteger32
Parsing Pid: 3093, 0xC15, typ: PtypInteger32
Parsing Pid: 3599, 0xE0F, typ: PtypBoolean
Parsing Pid: 4089, 0xFF9, typ: PtypBinary
Parsing Pid: 4094, 0xFFE, typ: PtypInteger32
Parsing Pid: 4095, 0xFFF, typ: PtypBinary
Parsing Pid: 12289, 0x3001, typ: PtypString8
Parsing Pid: 12290, 0x3002, typ: PtypString8
Parsing Pid: 12291, 0x3003, typ: PtypString8
Parsing Pid: 12299, 0x300B, typ: PtypBinary
Parsing Pid: 14592, 0x3900, typ: PtypInteger32
Parsing Pid: 14597, 0x3905, typ: PtypInteger32
Parsing Pid: 14846, 0x39FE, typ: PtypString8
Parsing Pid: 14847, 0x39FF, typ: PtypString8
Parsing Pid: 14848, 0x3A00, typ: PtypString8
Parsing Pid: 14880, 0x3A20, typ: PtypString8
Parsing Pid: 14912, 0x3A40, typ: PtypBoolean
Parsing Pid: 14961, 0x3A71, typ: PtypInteger32
Parsing Pid: 15617, 0x3D01, typ: PtypBinary
Parsing Pid: 24542, 0x5FDE, typ: PtypInteger32
Parsing Pid: 24543, 0x5FDF, typ: PtypInteger32
Parsing Pid: 24566, 0x5FF6, typ: PtypString8
Parsing Pid: 24567, 0x5FF7, typ: PtypBinary
Parsing Pid: 24573, 0x5FFD, typ: PtypInteger32
Parsing Pid: 24575, 0x5FFF, typ: PtypInteger32
Parsing Pid: 4086, 0xFF6, typ: PtypBinary
Parsing Pid: 12288, 0x3000, typ: PtypInteger32
Parsing Pid: 3617, 0xE21, typ: PtypInteger32
Unknown property: Unknown, value: 0
Parsing Pid: 4094, 0xFFE, typ: PtypInteger32
Unknown property: PidTagObjectType, value: 7
Parsing Pid: 4084, 0xFF4, typ: PtypInteger32
Unknown property: PidTagAccess, value: 2
Parsing Pid: 4087, 0xFF7, typ: PtypInteger32
Unknown property: PidTagAccessLevel, value: 0
Parsing Pid: 14085, 0x3705, typ: PtypInteger32
Unknown property: PidTagAttachMethod, value: 1
Parsing Pid: 14091, 0x370B, typ: PtypInteger32
Unknown property: PidTagRenderingPosition, value: -1
Parsing Pid: 4089, 0xFF9, typ: PtypBinary
Unknown property: PidTagRecordKey, value: [B@358e39c8
Parsing Pid: 12289, 0x3001, typ: PtypString8
Unknown property: Unknown, value: image001.png
Parsing Pid: 12295, 0x3007, typ: PtypTime
Unknown property: PidTagCreationTime, value: 2022-06-07T22:14:31.417137
Parsing Pid: 12296, 0x3008, typ: PtypTime
Unknown property: PidTagLastModificationTime, value: 2022-06-07T22:14:32.729532
Parsing Pid: 14081, 0x3701, typ: PtypBinary
Parsing Pid: 14082, 0x3702, typ: PtypBinary
Unknown property: PidTagAttachEncoding, value: [B@52469f77
Parsing Pid: 14083, 0x3703, typ: PtypString8
Unknown property: Unknown, value: .png
Parsing Pid: 14084, 0x3704, typ: PtypString8
Unknown property: Unknown, value: image001.png
Parsing Pid: 14087, 0x3707, typ: PtypString8
Unknown property: Unknown, value: image001.png
Parsing Pid: 14094, 0x370E, typ: PtypString8
Unknown property: Unknown, value: image/png
Parsing Pid: 14098, 0x3712, typ: PtypString8
Unknown property: Unknown, value: image001.png@01D87B1E.48246650
Parsing Pid: 14100, 0x3714, typ: PtypInteger32
Unknown property: PidTagAttachFlags, value: 4
Parsing Pid: 14109, 0x371D, typ: PtypBinary
Unknown property: Unknown, value: [B@7afd7971
Parsing Pid: 14860, 0x3A0C, typ: PtypString8
Unknown property: Unknown, value: EnUs
Parsing Pid: 32762, 0x7FFA, typ: PtypInteger32
Unknown property: PidTagAttachmentLinkId, value: 0
Parsing Pid: 32763, 0x7FFB, typ: PtypTime
Unknown property: PidTagExceptionStartTime, value: 4501-01-01T00:00
Parsing Pid: 32764, 0x7FFC, typ: PtypTime
Unknown property: PidTagExceptionEndTime, value: 4501-01-01T00:00
Parsing Pid: 32765, 0x7FFD, typ: PtypInteger32
Unknown property: PidTagAttachmentFlags, value: 8
Parsing Pid: 32766, 0x7FFE, typ: PtypBoolean
Unknown property: PidTagAttachmentHidden, value: true
Parsing Pid: 32767, 0x7FFF, typ: PtypBoolean
Unknown property: PidTagAttachmentContactPhoto, value: false
Parsing Pid: -32768, 0xFFFF8000, typ: PtypString8
Unknown property: Unknown, value: 
Parsing Pid: -32767, 0xFFFF8001, typ: PtypBoolean
Unknown property: Unknown, value: false
```
Some properties have different Ptyp from what have been defined in the code.
`0x3001` for instance, it is defined in `Pid.java` as `PidTagDisplayName(0x3001, PtypString)`, while what I got from log is `PtypString8`. I know the code follows MS document (https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/f6ab1613-aefe-447d-a49c-18217230b148), but seems my msg file doesn't follow that.

The older version of MsgViewer works fine for the same msg file, but the latest release (22 May) doesn't work.
I think it is because the Ptyp filter was added
https://github.com/lolo101/MsgViewer/commit/460ed5abb352b9cb30b9a694d834b92eaf9cee52#diff-2c91ecffe3e6950ee28ee9549cae88421b88acd247596de271a6be80a472d696

If I comment out `.filter(value -> value.typ == typ)`, it works fine, but it's might not what you want to change, so raising an issue here instead of sending pull request.

**Comment by lolo101** [comment]
Hi @oneryx and thanks for the report !

Indeed the filter is necessary because you have properties with same id that differ only b their type. For instance
```java
    PidTagBodyHtml(0x1013, PtypString),
    PidTagHtml(0x1013, PtypBinary),
```
However I would not be surprised there are messages that do not follow Microsoft specs :)

The stacktrace shows the missing property is PidTagAttachFilename on a file attachment.
The logs shows:
```
Parsing Pid: 14084, 0x3704, typ: PtypString8
Unknown property: Unknown, value: image001.png
```
I believe that's the culprit.

I'll think about a way to circumvent the issue. I'll let you know

**Comment by lolo101** [comment]
Hi @oneryx,

I think I have a fix but I would like to test it on your message.
Is it possible for you to send me the problematic message or another message with the same issue so I can validate the fix?

Thank you very much!

**Comment by oneryx** [comment]
Hi @lolo101,

I cannot publish the original email because it's from work, if you can create a new branch with fixes, I can help testing with it.

But I reproduced the issue by sending email with attachment in outlook, and save the received email as `test.msg` file.
I was trying to send the `test.msg` file to another account by email, outlook/gmail automatically converted it to `test.eml` file, there is no issue for MsgViewer to open it.

Then, I saved the received email as  `test.msg`  and `test-unicode.msg` (there is an option to save as unicode), MsgViewer can open `test-unicode.msg` but not  `test.msg`.

Please check the 3 files mentioned about in [test.zip](https://github.com/lolo101/MsgViewer/files/8987902/test.zip)

**Comment by lolo101** [comment]
Thank you very much for the test message @oneryx. The fix could open the message without any error.

Don't hesitate to reopen the issue if needed

**Comment by oneryx** [comment]
Thanks a lot @lolo101, I tested with original .msg file I got the issue, it can be opened correctly with the fix :+1:
