### ISSUE TITLE
Works on Windows 10 with openjdk 11 but is not opening for me in Linux

### ISSUE THREAD

**Issue by robertstrom** [lolo101/MsgViewer#118]
Hello,

I was able to use the program successfully on a Windows 10 computer with the current openjdk 11 installed, but I am having issues launching the jar file on my Linux desktop computer. The Linux computer is reporting this for the java version

```
└─(14:49:32)──> java --version                                                                                    ──(Mon,Jul25)─┘
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1, mixed mode, sharing)
```
This is what I am seeing when I try to run it on my Pop!_OS (Ubuntu based) 22.04 system. Would love to have the ability to view .eml / .msg files on my Linux computer (I do a fair amount of incident response / forensic work in my job). Hopefully this will end up working. Let me know if you need any other information.

Thanks very much

Robert

```
└─(14:49:38)──> java -jar msgviewer.jar                                                                           ──(Mon,Jul25)─┘
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
14:49:47.815 [main] ERROR at.redeye.FrameWork.base.Setup - File /home/rstrom/.MSGViewer/MSGViewer.properties existiert noch nicht.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2651)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1399)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1397)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1396)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1429)
	at java.desktop/java.awt.Component.<clinit>(Component.java:621)
	at at.redeye.FrameWork.base.translation.MLHelper.loadPropsFile(MLHelper.java:30)
	at at.redeye.FrameWork.base.translation.MLHelper.loadTrans(MLHelper.java:73)
	at at.redeye.FrameWork.base.translation.MLHelper.autoLoadCurrentLocale(MLHelper.java:80)
	at at.redeye.FrameWork.base.translation.MLHelper.<init>(MLHelper.java:24)
	at at.redeye.FrameWork.base.LocalRoot.setLanguageTranslationResourcePath(LocalRoot.java:222)
	at net.sourceforge.MSGViewer.ModuleLauncher.<init>(ModuleLauncher.java:23)
	at net.sourceforge.MSGViewer.ModuleLauncher.main(ModuleLauncher.java:27)
```

**Comment by robertstrom** [comment]
I just tested this on Kali Linux and it works on the latest version 2022.2

```
└─$ cat /etc/os-release                                    
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.2"
VERSION_ID="2022.2"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
```

```
└─$ uname -a          
Linux kali-2022 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux
```
The Kali java version information is:

```
└─$ java --version                                                                            
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-post-Debian-1, mixed mode, sharing)
```

HTH / Thanks

**Comment by lolo101** [comment]
Hi @robertstrom and thank you for the feedback!

From the error message on your Pop!_OS box I guess the installed JRE is headless. MsgViewer requires a headed JRE.
Please could you check which version of the openjdk-11 is installed by using this command:
`apt list openjdk-11*`

**Comment by robertstrom** [comment]
As you suggested, my system only had the openjdk-11-jdk-headless. I installed the openjdk-11-jdk and then was able to run the program without issue. Thank you very much!

**Comment by lolo101** [comment]
You're welcome ;)
