### ISSUE TITLE
Some MSG Files cause 'Cannot invoke "String.length()" because "s" is null'

### ISSUE THREAD

**Issue by datsteves** [lolo101/MsgViewer#124]
Hey,
when I run this command (file at the bottom)
```bash
$ java -jar msgviewer.jar -msg2eml testing.msg
```
I get following error on mac and on ubuntu but without the `Cannot invoke "String.length()" because "s" is null`

```bash
java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
	at javax.mail.internet.MimeUtility.checkAscii(MimeUtility.java:1413)
	at javax.mail.internet.MimeUtility.encodeWord(MimeUtility.java:712)
	at javax.mail.internet.MimeUtility.encodeText(MimeUtility.java:520)
	at net.sourceforge.MSGViewer.factory.mbox.MBoxWriterViaJavaMail.write(MBoxWriterViaJavaMail.java:80)
	at net.sourceforge.MSGViewer.factory.MessageSaver.write(MessageSaver.java:60)
	at net.sourceforge.MSGViewer.factory.MessageSaver.saveEMLFile(MessageSaver.java:54)
	at net.sourceforge.MSGViewer.factory.MessageSaver.saveMessage(MessageSaver.java:32)
	at net.sourceforge.MSGViewer.CLIFileConverter.processFile(CLIFileConverter.java:102)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.sourceforge.MSGViewer.CLIFileConverter.work(CLIFileConverter.java:76)
	at net.sourceforge.MSGViewer.ModuleLauncher.invoke(ModuleLauncher.java:62)
	at net.sourceforge.MSGViewer.ModuleLauncher.main(ModuleLauncher.java:27)
```
This is only happening with some MSGs files.
Tested it with the current release and with a build of the master branch.

## System Info
```bash
# MacOS
$ java -version

openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment Homebrew (build 18.0.2+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.2+0, mixed mode, sharing)

# Ubuntu
$ java -version

openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

## Files
Zipped Msg File:
[testing.zip](https://github.com/lolo101/MsgViewer/files/9402181/testing.zip)

Hope you can help :)

**Comment by lolo101** [comment]
Hi @datsteves and thank you very much for using MsgViewer, for the report and for the test file :)
I'll try reproduce the error asap and let you know

**Comment by lolo101** [comment]
Hi @datsteves I just committed a fix on the master branch.
Could you confirm the issue is fixed for you ? Then I can make a release

**Comment by datsteves** [comment]
thanks, @lolo101 for the fast response :)
just checked and yea it did fix it. 
Found a few other issues while testing with other msgs (that were failing due to the same reason), but that is something I have to look more into. As it can be an issue with other tools that run after this conversion too.
When I find something particular where its a conversion issue I will open a new ticket :)

thanks again ^^
