### ISSUE TITLE
Exception: Encountered <C_ESC_STRING>, Expected <STRING>

### ISSUE THREAD

**Issue by ThomasChr** [lolo101/MsgViewer#136]
I've got a mail which throws the following error:
```
2022-09-19T12:07:32,092 ERROR (AutoMBox.java:43): Exception: net.sourceforge.MSGViewer.rtfparser.ParseException: Encountered " <C_ESC_STRING> "\\\'b7 "" at line 608, column 160.
Was expecting:
    <STRING> ...

net.sourceforge.MSGViewer.rtfparser.ParseException: Encountered " <C_ESC_STRING> "\\\'b7 "" at line 608, column 160.
Was expecting:
    <STRING> ...

        at net.sourceforge.MSGViewer.rtfparser.RTFParser.generateParseException(RTFParser.java:394) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.rtfparser.RTFParser.jj_consume_token(RTFParser.java:332) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.rtfparser.RTFParser.unicode_char(RTFParser.java:210) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.rtfparser.RTFParser.group(RTFParser.java:172) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.rtfparser.RTFParser.group(RTFParser.java:184) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.rtfparser.RTFParser.group(RTFParser.java:184) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.rtfparser.RTFParser.group(RTFParser.java:184) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.rtfparser.RTFParser.parse(RTFParser.java:34) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.HtmlFromRtf.extractHtml(HtmlFromRtf.java:49) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.HtmlFromRtf.<init>(HtmlFromRtf.java:13) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerHelper.extractHTMLFromRTF(ViewerHelper.java:88) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.lambda$bodyText$1(ViewerPanel.java:343) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.resultOrElse(AutoMBox.java:41) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.bodyText(ViewerPanel.java:344) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.updateBody(ViewerPanel.java:324) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.doParse(ViewerPanel.java:430) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.lambda$new$0(AutoMBox.java:18) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.resultOrElse(AutoMBox.java:41) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.run(AutoMBox.java:59) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.parse(ViewerPanel.java:420) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.view(ViewerPanel.java:106) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.SingleWin.openFile(SingleWin.java:33) ~[msgviewer.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.sourceforge.MSGViewer.ModuleLauncher.invokeGui(ModuleLauncher.java:108) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ModuleLauncher.invoke(ModuleLauncher.java:64) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ModuleLauncher.main(ModuleLauncher.java:27) ~[msgviewer.jar:?]
```

I can't provide the mail because it's private. Just wanted to open the issue so that we can track it. Maybe I'll find it myself.
Any ideas from the top of your head?

**Comment by ThomasChr** [comment]
The error does come from this sign: https://www.codetable.net/decimal/8729
Here is one to test:
```
∙
```

I'm trying to get closer to the culprit, but my RTF and Unicode knowledge does only go that far...

**Comment by ThomasChr** [comment]
Changing RTFParser.jj like this seems to do the trick:
```
Index: MSGViewer/src/main/javacc/net/sourceforge/MSGViewer/rtfparser/RTFParser.jj
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/MSGViewer/src/main/javacc/net/sourceforge/MSGViewer/rtfparser/RTFParser.jj b/MSGViewer/src/main/javacc/net/sourceforge/MSGViewer/rtfparser/RTFParser.jj
--- a/MSGViewer/src/main/javacc/net/sourceforge/MSGViewer/rtfparser/RTFParser.jj	(revision a177966d6fac70c7364a71679a551a038e680053)
+++ b/MSGViewer/src/main/javacc/net/sourceforge/MSGViewer/rtfparser/RTFParser.jj	(date 1663594519333)
@@ -131,7 +131,7 @@
 }
 {
     code = <C_UNICODE>
-    <STRING>
+
     {
         current_group.addUnicodeChar( code.image );
     }
```

This will change the File RTFParser.java from this:
```java
  final public void unicode_char() throws ParseException {Token code;
    code = jj_consume_token(C_UNICODE);
    jj_consume_token(STRING);
current_group.addUnicodeChar( code.image );
}
```
to this:
```java
  final public void unicode_char() throws ParseException {Token code;
    code = jj_consume_token(C_UNICODE);
current_group.addUnicodeChar( code.image );
}
```

I think the jj_consume_token(STRING) isn't needed in this case - but I may be way off here!

Outcome: No exception and Unicode char is shown, but I'm not quite sure that I'm absolutely correct here.

**Comment by ThomasChr** [comment]
Okay, the error is gone, but it seems that the char has been duplicated now:
![image](https://user-images.githubusercontent.com/13014163/191033003-3e3c914b-81ad-4785-942e-1416876f8051.png)

So that doesn't seem to be the perfect fix.

**Comment by ThomasChr** [comment]
Some more info from here: https://www.zopatista.com/python/2012/06/06/rtf-and-unicode/
```
{\*\htmltag84 &#8729;}\htmlrtf \u8729\'95\htmlrtf0 
```
So this Sequence is actually two times the same char.
One in the form \uUNICODECODEPOINT and one in the form \'WIN1252_CODEPOINT

I'm not quite sure why this is the case...

**Comment by ThomasChr** [comment]
A few infos how the parser works: https://stackoverflow.com/questions/17310377/what-does-consume-mean-in-javacc

**Comment by ThomasChr** [comment]
Okay, so at the moment I have two different cases for the parser:

Number 1:
```
\u8729\'b7
```
This is Unicode 8729 followed by WIN-1252 B7 -> Both are the "bullet point" character.
So this should be parsed as:
(src/main/javacc/net/sourceforge/MSGViewer/rtfparser/RTFParser.jj)
C_UNICODE (where we get the code point) followed by C_ESC_STRING which we just ignore/consume.

BUT, a few lines along my mail I got the following:
```
\u-3929 ?;
```
And THIS one seems to be F0A7 (65536 - 3929 in Hex because above 32767 RTF wants Unicode Chars to be negative) which is in the private Unicode Characters Area. I have no clue what this char does mean or what it does there, but it seems we're not alone:
https://stackoverflow.com/questions/37166528/in-rtf-what-is-the-meaning-of-u-3913

So this sequence seems to be some weird character (which we don't care) but followed by the replacement character '?' - which is NOT an C_ESC_STRING - it's a normal STRING.

It seems our parser needs to handle both those cases, which it does not at the moment.

**Comment by ThomasChr** [comment]
The Pull Request will fix the problem.
I never ever wanted to go so deep into the (parser) rabbit hole, so be gentle to me :-)

**Comment by lolo101** [comment]
Hi @ThomasChr and thank you very much for your engagement :smiley: 

That's right the <STRING> you want to get rid of is the placeholder (the char that should be displayed when the parser does not support Unicode). However, it seems that in your case the placeholder is not a <STRING> but a <C_ESC_STRING> which is unexpected :slightly_smiling_face: 

I'll take a look at the PR as soon as I have a comfortable time ahead

**Comment by ThomasChr** [comment]
Take your time, no stress!
