### ISSUE TITLE
Cannot open a specific msg file

### ISSUE THREAD

**Issue by skalg** [lolo101/MsgViewer#26]
For only on msg file i'm getting an error and this file is readable but MS Outlook.

```
java -jar msgviewer.jar d.msg

14:30:26.187 [AWT-EventQueue-0] ERROR net.sourceforge.MSGViewer.MainWin - Exception: java.lang.RuntimeException: Unclosed block
Unclosed block
java.lang.RuntimeException: Unclosed block
        at javax.swing.text.html.CSSParser.parseTillClosed(CSSParser.java:463) ~[?:?]
        at javax.swing.text.html.CSSParser.parseAtRule(CSSParser.java:236) ~[?:?]
        at javax.swing.text.html.CSSParser.getNextStatement(CSSParser.java:174) ~[?:?]
        at javax.swing.text.html.CSSParser.parse(CSSParser.java:153) ~[?:?]
        at javax.swing.text.html.StyleSheet$CssParser.parse(StyleSheet.java:3258) ~[?:?]
        at javax.swing.text.html.StyleSheet.addRule(StyleSheet.java:314) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader.addCSSRules(HTMLDocument.java:4071) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader$HeadAction.end(HTMLDocument.java:3182) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader.handleEndTag(HTMLDocument.java:2897) ~[?:?]
        at javax.swing.text.html.parser.DocumentParser.handleEndTag(DocumentParser.java:253) ~[?:?]
        at javax.swing.text.html.parser.Parser.parse(Parser.java:2394) ~[?:?]
        at javax.swing.text.html.parser.DocumentParser.parse(DocumentParser.java:135) ~[?:?]
        at javax.swing.text.html.parser.ParserDelegator.parse(ParserDelegator.java:113) ~[?:?]
        at javax.swing.text.html.HTMLEditorKit.read(HTMLEditorKit.java:263) ~[?:?]
        at javax.swing.JEditorPane.setText(JEditorPane.java:1428) ~[?:?]
        at net.sourceforge.MSGViewer.ViewerPanel.updateBody(ViewerPanel.java:336) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.parse_int(ViewerPanel.java:606) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel$3.do_stuff(ViewerPanel.java:444) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.invoke(AutoMBox.java:64) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.<init>(AutoMBox.java:50) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel$3.<init>(ViewerPanel.java:440) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.parse(ViewerPanel.java:440) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.SingleWin.lambda$new$0(SingleWin.java:56) ~[msgviewer.jar:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) [?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) [?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) [?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
2021-03-16T14:30:26,187 ERROR (AutoMBox.java:67): Exception: java.lang.RuntimeException: Unclosed block
Unclosed block
java.lang.RuntimeException: Unclosed block
        at javax.swing.text.html.CSSParser.parseTillClosed(CSSParser.java:463) ~[?:?]
        at javax.swing.text.html.CSSParser.parseAtRule(CSSParser.java:236) ~[?:?]
        at javax.swing.text.html.CSSParser.getNextStatement(CSSParser.java:174) ~[?:?]
        at javax.swing.text.html.CSSParser.parse(CSSParser.java:153) ~[?:?]
        at javax.swing.text.html.StyleSheet$CssParser.parse(StyleSheet.java:3258) ~[?:?]
        at javax.swing.text.html.StyleSheet.addRule(StyleSheet.java:314) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader.addCSSRules(HTMLDocument.java:4071) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader$HeadAction.end(HTMLDocument.java:3182) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader.handleEndTag(HTMLDocument.java:2897) ~[?:?]
        at javax.swing.text.html.parser.DocumentParser.handleEndTag(DocumentParser.java:253) ~[?:?]
        at javax.swing.text.html.parser.Parser.parse(Parser.java:2394) ~[?:?]
        at javax.swing.text.html.parser.DocumentParser.parse(DocumentParser.java:135) ~[?:?]
        at javax.swing.text.html.parser.ParserDelegator.parse(ParserDelegator.java:113) ~[?:?]
        at javax.swing.text.html.HTMLEditorKit.read(HTMLEditorKit.java:263) ~[?:?]
        at javax.swing.JEditorPane.setText(JEditorPane.java:1428) ~[?:?]
        at net.sourceforge.MSGViewer.ViewerPanel.updateBody(ViewerPanel.java:336) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.parse_int(ViewerPanel.java:606) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel$3.do_stuff(ViewerPanel.java:444) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.invoke(AutoMBox.java:64) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.<init>(AutoMBox.java:50) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel$3.<init>(ViewerPanel.java:440) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.parse(ViewerPanel.java:440) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.SingleWin.lambda$new$0(SingleWin.java:56) ~[msgviewer.jar:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) [?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) [?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) [?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
2021-03-16T14:30:26,187 ERROR (AutoMBox.java:67): Exception: java.lang.RuntimeException: Unclosed block
Unclosed block
java.lang.RuntimeException: Unclosed block
        at javax.swing.text.html.CSSParser.parseTillClosed(CSSParser.java:463) ~[?:?]
        at javax.swing.text.html.CSSParser.parseAtRule(CSSParser.java:236) ~[?:?]
        at javax.swing.text.html.CSSParser.getNextStatement(CSSParser.java:174) ~[?:?]
        at javax.swing.text.html.CSSParser.parse(CSSParser.java:153) ~[?:?]
        at javax.swing.text.html.StyleSheet$CssParser.parse(StyleSheet.java:3258) ~[?:?]
        at javax.swing.text.html.StyleSheet.addRule(StyleSheet.java:314) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader.addCSSRules(HTMLDocument.java:4071) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader$HeadAction.end(HTMLDocument.java:3182) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader.handleEndTag(HTMLDocument.java:2897) ~[?:?]
        at javax.swing.text.html.parser.DocumentParser.handleEndTag(DocumentParser.java:253) ~[?:?]
        at javax.swing.text.html.parser.Parser.parse(Parser.java:2394) ~[?:?]
        at javax.swing.text.html.parser.DocumentParser.parse(DocumentParser.java:135) ~[?:?]
        at javax.swing.text.html.parser.ParserDelegator.parse(ParserDelegator.java:113) ~[?:?]
        at javax.swing.text.html.HTMLEditorKit.read(HTMLEditorKit.java:263) ~[?:?]
        at javax.swing.JEditorPane.setText(JEditorPane.java:1428) ~[?:?]
        at net.sourceforge.MSGViewer.ViewerPanel.updateBody(ViewerPanel.java:336) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.parse_int(ViewerPanel.java:606) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel$3.do_stuff(ViewerPanel.java:444) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.invoke(AutoMBox.java:64) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.<init>(AutoMBox.java:50) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel$3.<init>(ViewerPanel.java:440) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.parse(ViewerPanel.java:440) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.SingleWin.lambda$new$0(SingleWin.java:56) ~[msgviewer.jar:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) [?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) [?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) [?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
2021-03-16T14:30:26,187 ERROR (AutoMBox.java:67): Exception: java.lang.RuntimeException: Unclosed block
Unclosed block
java.lang.RuntimeException: Unclosed block
        at javax.swing.text.html.CSSParser.parseTillClosed(CSSParser.java:463) ~[?:?]
        at javax.swing.text.html.CSSParser.parseAtRule(CSSParser.java:236) ~[?:?]
        at javax.swing.text.html.CSSParser.getNextStatement(CSSParser.java:174) ~[?:?]
        at javax.swing.text.html.CSSParser.parse(CSSParser.java:153) ~[?:?]
        at javax.swing.text.html.StyleSheet$CssParser.parse(StyleSheet.java:3258) ~[?:?]
        at javax.swing.text.html.StyleSheet.addRule(StyleSheet.java:314) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader.addCSSRules(HTMLDocument.java:4071) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader$HeadAction.end(HTMLDocument.java:3182) ~[?:?]
        at javax.swing.text.html.HTMLDocument$HTMLReader.handleEndTag(HTMLDocument.java:2897) ~[?:?]
        at javax.swing.text.html.parser.DocumentParser.handleEndTag(DocumentParser.java:253) ~[?:?]
        at javax.swing.text.html.parser.Parser.parse(Parser.java:2394) ~[?:?]
        at javax.swing.text.html.parser.DocumentParser.parse(DocumentParser.java:135) ~[?:?]
        at javax.swing.text.html.parser.ParserDelegator.parse(ParserDelegator.java:113) ~[?:?]
        at javax.swing.text.html.HTMLEditorKit.read(HTMLEditorKit.java:263) ~[?:?]
        at javax.swing.JEditorPane.setText(JEditorPane.java:1428) ~[?:?]
        at net.sourceforge.MSGViewer.ViewerPanel.updateBody(ViewerPanel.java:336) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.parse_int(ViewerPanel.java:606) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel$3.do_stuff(ViewerPanel.java:444) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.invoke(AutoMBox.java:64) ~[msgviewer.jar:?]
        at at.redeye.FrameWork.base.AutoMBox.<init>(AutoMBox.java:50) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel$3.<init>(ViewerPanel.java:440) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.ViewerPanel.parse(ViewerPanel.java:440) ~[msgviewer.jar:?]
        at net.sourceforge.MSGViewer.SingleWin.lambda$new$0(SingleWin.java:56) ~[msgviewer.jar:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) [?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) [?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) [?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```

**Comment by lolo101** [comment]
Related to #11 
I believe the conditionals `<!--[if gte mso 9]>` are not handled by the parser.
Investigating this way

**Comment by lolo101** [comment]
The issue seems fixed by refactoring the RTF parser. However, the example message shows incorrect parsing of nester RTF groups:
```
{\lang1036 \htmlrtf0  Toto Mail
{\*\htmltag84 &lt;}\htmlrtf <\htmlrtf0 toto.mail@skynet.com
{\*\htmltag84 &gt;}\htmlrtf >\htmlrtf0
```
Yields this invalid HTML: `Toto Mail &lt;<toto.mail@skynet.com&gt;>` because groups are treated as a list instead of a tree. Hence when a group closes, instead of popping the previous group the parser keeps using the same group leading to incorrect text content for this group.

The RTF Parser still requires effort...
