### ISSUE TITLE
MSGViewer fails to convert .msg email to either .mbox or *.eml on OS X High Sierra

### ISSUE THREAD

**Issue by lolo101** [lolo101/MsgViewer#3]
Runtime: Java(TM) SE Runtime Environment 10+46
System: Mac OS X version 10.13.6 running on x86_64; UTF-8; en_US (nb)

+++

    MSGViewer cmd line mail format conversion fails with the following error:

$ java -jar "/Users/user1/NetBeansProjects/MSGViewer/dist/MSGViewer.jar" -msg2mbox *.msg
2018-11-12 15:18:26,128 INFO (CLIFileConverter.java:103): conversion source file: FW_ City of Santa Cruz - Briefing Materials.msg
java.lang.NullPointerExceptionjava.lang.NullPointerException
at net.sourceforge.MSGViewer.CLIFileConverter.processFile(CLIFileConverter.java:114)
at net.sourceforge.MSGViewer.CLIFileConverter.work(CLIFileConverter.java:89)
at net.sourceforge.MSGViewer.ModuleLauncher.invoke(ModuleLauncher.java:80)
at net.sourceforge.MSGViewer.ModuleLauncher.main(ModuleLauncher.java:178)
2018-11-12 15:18:26,137 INFO (CLIFileConverter.java:103): conversion source file: FW_ Quote from Report from City of Santa Cruz - Briefing Materials (1).msg
java.lang.NullPointerExceptionjava.lang.NullPointerException
at net.sourceforge.MSGViewer.CLIFileConverter.processFile(CLIFileConverter.java:114)
at net.sourceforge.MSGViewer.CLIFileConverter.work(CLIFileConverter.java:89)
at net.sourceforge.MSGViewer.ModuleLauncher.invoke(ModuleLauncher.java:80)
at net.sourceforge.MSGViewer.ModuleLauncher.main(ModuleLauncher.java:178)
…

    Opening a *.msg file in the GUI and then saving it back to a .msg works, saved as text. Saving the same file to .mbox or .eml fails with the following error messages, respectively:

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javax/activation/DataSource
at net.sourceforge.MSGViewer.factory.MessageParserFactory.saveMBoxFile(MessageParserFactory.java:107)
at net.sourceforge.MSGViewer.factory.MessageParserFactory.saveMessage(MessageParserFactory.java:90)
at net.sourceforge.MSGViewer.ViewerPanel.exportFile(ViewerPanel.java:887)
at net.sourceforge.MSGViewer.SingleWin$12.do_stuff(SingleWin.java:301)
at at.redeye.FrameWork.base.AutoMBox.invoke(AutoMBox.java:64)
at at.redeye.FrameWork.base.AutoMBox.<init>(AutoMBox.java:50)
at net.sourceforge.MSGViewer.SingleWin$12.<init>(SingleWin.java:287)
at net.sourceforge.MSGViewer.SingleWin.jMFileSaveActionPerformed(SingleWin.java:287)
at net.sourceforge.MSGViewer.SingleWin.access$400(SingleWin.java:31)
at net.sourceforge.MSGViewer.SingleWin$4.actionPerformed(SingleWin.java:146)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:980)
at java.desktop/com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1024)
at java.desktop/java.awt.Component.processMouseEvent(Component.java:6589)
at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
at java.desktop/java.awt.Component.processEvent(Component.java:6354)
at java.desktop/java.awt.Container.processEvent(Container.java:2260)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2318)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4906)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2304)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
... 49 more</init></init>

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javax/activation/DataSource
at net.sourceforge.MSGViewer.factory.MessageParserFactory.saveEMLFile(MessageParserFactory.java:120)
at net.sourceforge.MSGViewer.factory.MessageParserFactory.saveMessage(MessageParserFactory.java:92)
at net.sourceforge.MSGViewer.ViewerPanel.exportFile(ViewerPanel.java:887)
at net.sourceforge.MSGViewer.SingleWin$12.do_stuff(SingleWin.java:301)
at at.redeye.FrameWork.base.AutoMBox.invoke(AutoMBox.java:64)
at at.redeye.FrameWork.base.AutoMBox.<init>(AutoMBox.java:50)
at net.sourceforge.MSGViewer.SingleWin$12.<init>(SingleWin.java:287)
at net.sourceforge.MSGViewer.SingleWin.jMFileSaveActionPerformed(SingleWin.java:287)
at net.sourceforge.MSGViewer.SingleWin.access$400(SingleWin.java:31)
at net.sourceforge.MSGViewer.SingleWin$4.actionPerformed(SingleWin.java:146)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:980)
at java.desktop/com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1024)
at java.desktop/java.awt.Component.processMouseEvent(Component.java:6589)
at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
at java.desktop/java.awt.Component.processEvent(Component.java:6354)
at java.desktop/java.awt.Container.processEvent(Container.java:2260)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2318)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4906)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2304)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
... 49 more

**Comment by lolo101** [comment]
javax.activation has been deprecated in JDK9 : https://docs.oracle.com/javase/9/docs/api/java.activation-summary.html

**Comment by lolo101** [comment]
Should not happen with the uber-jar
